### ISSUE TITLE
gives immediate crash on north american sites

### ISSUE THREAD

**Issue by narration-sd** [mikestecker/craft3-videoembedder#1]
Crashes on attempt to install. 

This appears to be about a missing language config file, maybe more, but I suspect shouldn't be looking for one unless you are specifying a locale different from the English the code writes to. 

Traced through to a point, but ran out of time, so just reporting. 

Part of the problem may be that the proposed 'category' name doesn't match what's in `translation['category']` of the method where the crash comes, ` I18N->getMessageSource`.  In the method call, `video-embedder` is passed, but the array has `craft3-videoembedder`.

I tried changing the var via debugger to `craft3-videoembedder`, but the crash came again, same spot, so it must get called again; and as said, ran out of time to go farther -- maybe the root of this mismatch is the problem though. It did install after the change -- but then brings down the entire CP with the trace, so watch out...removing the craft_plugins row is the way to recover.

Plugin itself, a nice idea, thank for doing it. I haven't gotten ahold of Trevor Davis to Pull Request or publish a Craft 3 port I did of his Video Embed -- looks like yours does more.

Testing on a up-to-moment dev-develop, aliased to its root of beta 23, trace attached here: 
[trace-video-embedder (1).txt](https://github.com/mikestecker/craft3-videoembedder/files/1204118/trace-video-embedder.1.txt)

**Comment by narration-sd** [comment]
p.s. (sorry, really had to leave this in a hurry) I don't have intl installed on the Vagrant box. I loaded @takobell's suggested file from here:  https://github.com/craftcms/locales . I used the en-US one.

**Comment by mikestecker** [comment]
Thanks for the report. I'll have a look. I've never written a plugin before and simply used the plugin generator as this is not my strong suite.

**Comment by mikestecker** [comment]
I think I found the issue... When I used the generator, I had used the name `video-embedder` and went through renaming it to `craft3-videoembedder` to follow along with @nystudio107's naming convention but must have changed it in a spot where I shouldn't have. Anyway, I just pushed a fix.

**Comment by narration-sd** [comment]
Hi Mike -- the fix seems to have got it:
- installs and uninstalls, reinstalls without apparent  problems now
- both video and poster image retrieve fine
- at least for standard en-US Site locale, no extra locale config is necessary even if `intl` isn't installed for php
- both YouTube and Vimeo (https://vimeo.com/27877044) seem to come out well

One thing you need still to update is the Example set in the Readme.  The Twig signatures need to be `craft.videoEmbedder.get...`, or another stack trace occurs due to mismatch. 

Ah, see you did do this on Viget base -- good move.

Just a thought further for the Readme -- might be helpful to offer a little more fleshed out examples, such as 4x3 and 16x9 (seems default Vimeo) image and iframe sizes, also the allowfullscreen directive, to hint how options are controlled.  Something like:

`<iframe` width="640" height="360" 
  src="{{ craft.videoEmbedder.getEmbedUrl('https://vimeo.com/27877044') }}" allowfullscreen></iframe>`

Of course, don't want to get in too deep here, as options etc. are tricky -- players are tricky :) . I am still seeing if videojs will really sort out in its modern version for all the things I'd like on YouTubes, and the tea leaves have not been encouraging, but one may hope....

Seems all to do the trick, Mike -- am sure others will be glad to use it -- Clive
