### ISSUE TITLE
Removed (vimeo) videos cause 500 errors on site

### ISSUE THREAD

**Issue by billythekid** [mikestecker/craft3-videoembedder#15]
If I get time I'll try to issue a PR for this as I know you're not a PHP dev to trade.

Essentially the bug is if a (I've only seen this on Vimeo so far) video URL is embedded and that video is subsequently deleted/removed the plugin errors out, pulling down the page the embed should happen on, rather than returning an empty string or whatever. 

It appears to be an unhandled Embed\Exceptions\InvalidUrlException exception.

Example URL: https://vimeo.com/291962166

**Comment by mikestecker** [comment]
@billythekid Wow thanks! I think this will close most of the open issues here too (#7, #12 & #13). I really appreciate it. Yeah between the job and my lack of PHP knowledge, it's been difficult for me to upkeep this, so I really appreciate help like this.

I'll pull it down and test as soon as I get a little bit of free time hopefully today.

**Comment by Coysh** [comment]
@mikestecker - any updates of pushing this? Would be really useful to update our site to this.

**Comment by mikestecker** [comment]
@Coysh @billythekid So sorry for the delay! I haven't had a chance to test yet but I'll go ahead and merge in and release right now.

I've been so far removed from Craft projects lately, I just haven't had a chance. Can you please test thoroughly and let me know if there's any issues?
