### ISSUE TITLE
getEmbedUrl errors if Vimeo url doesn't exist

### ISSUE THREAD

**Issue by mijewe** [mikestecker/craft3-videoembedder#18]
If you enter a Vimeo link that doesn't exist, Craft will throw an error, rather than fail gracefully.

Steps to reproduce:
1. use getEmbedUrl() with a broken url, eg https://vimeo.com/23584222

**Comment by mijewe** [comment]
#19

**Comment by mikestecker** [comment]
Thanks for the fix! I'll push out a release
