### ISSUE TITLE
InvalidUrlException for all Youtube urls

### ISSUE THREAD

**Issue by dgrigg** [mikestecker/craft3-videoembedder#6]
This YouTube url 'https://www.youtube.com/watch?v=UAo_xJE1ta8' (or any I put in) 
Embed\Exceptions\InvalidUrlException
Invalid url 'https://www.youtube.com/watch?v=UAo_xJE1ta8' (Status code 0)

```php
if ($response->getError() === null) {
            $exception = new Exceptions\InvalidUrlException(sprintf("Invalid url '%s' (Status code %s)", (string) $url, $response->getStatusCode()));
        } else {
            $exception = new Exceptions\InvalidUrlException($response->getError());
        }
```

Plugin Version: 1.0.8
Craft: 3.0.1

**Comment by mikestecker** [comment]
Can you share the twig template code you are using? I've tried your URL that you provided and it seems to work in my tests.

**Comment by mikestecker** [comment]
@dgrigg I believe this is the same issue as #5, the video might not allow embedding.

I haven't pushed out this release yet but I added a catch for when the URL doesn't return a result, either that there's no video at the URL or embedding is disabled. So, once I push out the update (soon) you'll be able to check in your twig template:

```
{% set embed = craft.videoEmbedder.embed(videoUrl, {autoplay: 1, rel: 0, theme: 'dark'}) %}

{% if embed | length %}
    your code here
{% endif %}
```
